In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.backends.backend_pdf
import matplotlib as mpl
from matplotlib.colors import LinearSegmentedColormap, ListedColormap

In [7]:
def writeNewtxt(file_path, df):
    """Writes a pandas dataframe into txt, columns separated by tabs ("\t")
    """
    f = open(file_path, 'w')
    df_cols = ""
    for col in df.columns[:-1]:
        df_cols += str(col) + "\t"
    df_cols += df.columns.values[-1]+ "\n"
    f.write(str(df_cols))
    for row in df.index:
        df_row = ""
        for col in df.columns[:-1]:
            df_row += str(df[col][row]) + "\t"
        df_row += str(df[df.columns[-1]][row])+ "\n"
        f.write(df_row)
    f.close

In [2]:
cytoband_read = r"C:\Users\ext.andre.santos\Documents\Privacy_sens_human_genome\A_map_of_privacy-sensitivity_in_human_genomes-main\cytobands\cytobandFiltered_processed_str_dr_dg_gv_sorted.txt"
cb_df = pd.read_csv(cytoband_read, sep="\t")
cb_df

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,TandemRepeats_dens,STRs_dens,LTRs_dens,DRs_density,...,five_prime_UTRIntron_density,five_prime_UTRExon_density,three_prime_UTRs_density,three_prime_UTRIntron_density,three_prime_UTRExon_density,exons_density,SNP_density,Indel_density,Inserts_density,Deletes_density
0,chr1,0,2299999,p36.33,gneg,2299999,0.087516,0.006384,0.084476,0.326328,...,0.005135,0.005529,0.026310,0.025853,0.000456,0.133749,0.022000,0.006463,0.001590,0.004900
1,chr1,2300000,5299999,p36.32,gpos25,2999999,0.084077,0.013902,0.079223,0.281556,...,0.001761,0.001512,0.019776,0.019406,0.000370,0.060012,0.033405,0.008639,0.002013,0.006659
2,chr1,5300000,7099999,p36.31,gneg,1799999,0.056236,0.012909,0.051421,0.275410,...,0.002073,0.003586,0.025848,0.025715,0.000133,0.056062,0.030704,0.009019,0.002377,0.006688
3,chr1,7100000,9099999,p36.23,gpos25,1999999,0.049082,0.013229,0.042217,0.404844,...,0.002070,0.001499,0.015875,0.015746,0.000129,0.034280,0.028061,0.009503,0.002497,0.007044
4,chr1,9100000,12499999,p36.22,gneg,3399999,0.055881,0.011072,0.048928,0.404047,...,0.002176,0.002777,0.029553,0.028516,0.001037,0.066018,0.028159,0.008768,0.002322,0.006476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,chrY,12400000,17099999,q11.221,gpos50,4699999,0.036956,0.014211,0.029356,0.015158,...,0.000344,0.000583,0.002534,0.002459,0.000075,0.009953,0.000000,0.000000,0.000000,0.000000
858,chrY,17100000,19599999,q11.222,gneg,2499999,0.061662,0.015902,0.052790,0.012965,...,0.000338,0.000008,0.000937,0.000635,0.000302,0.033020,0.000000,0.000000,0.000000,0.000000
859,chrY,19600000,23799999,q11.223,gpos50,4199999,0.082234,0.005789,0.078347,0.006441,...,0.000037,0.000503,0.002733,0.002733,0.000000,0.021283,0.000000,0.000000,0.000000,0.000000
860,chrY,23800000,26599999,q11.23,gneg,2799999,0.026278,0.009164,0.020721,0.001822,...,0.000345,0.000308,0.002016,0.001749,0.000267,0.022278,0.000000,0.000000,0.000000,0.000000
861,chrY,26600000,57227414,q12,gvar,30627414,0.005530,0.001643,0.004251,0.000594,...,0.000000,0.000005,0.000094,0.000094,0.000000,0.000460,0.000000,0.000000,0.000000,0.000000

In [4]:
def surnameInf_metric():
    surname_inf_metric = []
    for row in cb_df.index:
        if cb_df["Chromossome"][row] == "chrY":
            if cb_df["Citoband"][row] in ["p11.2", "p11.23", "q11.21", "q11.221", "q11.222", "q11.223"]:
               surname_inf_metric.append(cb_df["STRs_dens"][row] * 1)
            else:
                surname_inf_metric.append(0)
        else:
             surname_inf_metric.append(0)
    
    cb_df.insert(len(cb_df.columns), "metric_surnameInf", surname_inf_metric, True)

In [5]:
surnameInf_metric()

In [6]:
cb_df

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,TandemRepeats_dens,STRs_dens,LTRs_dens,DRs_density,...,five_prime_UTRExon_density,three_prime_UTRs_density,three_prime_UTRIntron_density,three_prime_UTRExon_density,exons_density,SNP_density,Indel_density,Inserts_density,Deletes_density,metric_surnameInf
0,chr1,0,2299999,p36.33,gneg,2299999,0.087516,0.006384,0.084476,0.326328,...,0.005529,0.026310,0.025853,0.000456,0.133749,0.022000,0.006463,0.001590,0.004900,0.000000
1,chr1,2300000,5299999,p36.32,gpos25,2999999,0.084077,0.013902,0.079223,0.281556,...,0.001512,0.019776,0.019406,0.000370,0.060012,0.033405,0.008639,0.002013,0.006659,0.000000
2,chr1,5300000,7099999,p36.31,gneg,1799999,0.056236,0.012909,0.051421,0.275410,...,0.003586,0.025848,0.025715,0.000133,0.056062,0.030704,0.009019,0.002377,0.006688,0.000000
3,chr1,7100000,9099999,p36.23,gpos25,1999999,0.049082,0.013229,0.042217,0.404844,...,0.001499,0.015875,0.015746,0.000129,0.034280,0.028061,0.009503,0.002497,0.007044,0.000000
4,chr1,9100000,12499999,p36.22,gneg,3399999,0.055881,0.011072,0.048928,0.404047,...,0.002777,0.029553,0.028516,0.001037,0.066018,0.028159,0.008768,0.002322,0.006476,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,chrY,12400000,17099999,q11.221,gpos50,4699999,0.036956,0.014211,0.029356,0.015158,...,0.000583,0.002534,0.002459,0.000075,0.009953,0.000000,0.000000,0.000000,0.000000,0.014211
858,chrY,17100000,19599999,q11.222,gneg,2499999,0.061662,0.015902,0.052790,0.012965,...,0.000008,0.000937,0.000635,0.000302,0.033020,0.000000,0.000000,0.000000,0.000000,0.015902
859,chrY,19600000,23799999,q11.223,gpos50,4199999,0.082234,0.005789,0.078347,0.006441,...,0.000503,0.002733,0.002733,0.000000,0.021283,0.000000,0.000000,0.000000,0.000000,0.005789
860,chrY,23800000,26599999,q11.23,gneg,2799999,0.026278,0.009164,0.020721,0.001822,...,0.000308,0.002016,0.001749,0.000267,0.022278,0.000000,0.000000,0.000000,0.000000,0.000000
861,chrY,26600000,57227414,q12,gvar,30627414,0.005530,0.001643,0.004251,0.000594,...,0.000005,0.000094,0.000094,0.000000,0.000460,0.000000,0.000000,0.000000,0.000000,0.000000

In [8]:
cytoband_write = r"C:\Users\ext.andre.santos\Documents\Privacy_sens_human_genome\A_map_of_privacy-sensitivity_in_human_genomes-main\cytobands\cytobandFiltered_processed_metrics_sorted.txt"

In [9]:
writeNewtxt(cytoband_write, cb_df)